config/routes.rb
Rails.application.routes.draw do
  resources :days 
  resources :events
  get 'homepage/index'
  root 'homepage#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
   
end

app/models/day.rb
class Day < ApplicationRecord
    has_many :events, dependent: :delete_all
    
    
    def to_s
        "#{title}"
    end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :day, :optional => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
    def index
      @days = Day.all
    end

    def show
    @day = Day.find(params[:id])
    end

    def new
      @day = Day.new
    end

    def create
      @day = Day.new(day_params)
      
      
      if @day.save
        redirect_to @day
      else
        render 'new'
      end
    end

    def edit
    @day = Day.find(params[:id])
    end

    def update
      @day = Day.find(params[:id])
      
    if @day.update(day_params)
    redirect_to @day
    else
    render 'edit'
    end
    end

    def destroy
      @day = Day.find(params[:id])
      @day.destroy
      redirect_to days_path
    end    
end

    private
    def day_params
      params.require(:day).permit(:title, :text)
    end

app/controllers/events_controller.rb
class EventsController < ApplicationController
     
      def index
        @events = Event.all
      end

      def show
      @event = Event.find(params[:id])
      end

      def new
        @event = Event.new
      end

      def create
        @event = Event.new(event_params)
        
        if @event.save
        redirect_to @event
        else
        render 'new'
        end
      end
  

      def edit
      @event = Event.find(params[:id])
      end

      def update
        @event = Event.find(params[:id])
        
      if @event.update(event_params)
        redirect_to @event
      else
        render 'edit'
      end
      end

      def destroy
        @event = Event.find(params[:id])
        @event.destroy
        redirect_to events_path
      end
end

      private
      def event_params
        params.require(:event).permit(:title, :body, :day_id)
      end

    

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/views/days/_form.html.erb
<link rel ="stylesheet" type= "text/css" href = "css/new_activity.css">
<%= form_for (@day) do |f| %>



<% if @day.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@day.errors.count, "error") %> prohibited
        this day from being saved:
      </h2>
      <ul>
        <% @day.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Edit Day</h1>
 <link rel ="stylesheet" type= "text/css" href = "css/new_activity.css">
 <%= render 'form' %>
 
 <% link_to 'Back', days_path %>

app/views/days/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Of All Days</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.title %></td>
        <td><%= day.text %></td>
        <td><%= link_to 'Show', day %></td>
        <td><%= link_to 'Edit', edit_day_path(day) %></td>
        <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_day_path %>
<a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/">Homepage</a>

app/views/days/new.html.erb
<h1>New Day</h1>
<%= render 'form' %>

<%= form_for :day, url:days_path do |f| %>

<% if @day.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@day.errors.count, "error") %> prohibited
        this day from being saved:
      </h2>
      <ul>
        <% @day.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    
  <% end %>
  
  
<% end %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @day.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @day.text %>
</p>
<%= link_to 'Day List', days_path %>


<p><%= link_to 'Delete', @day, method: 'delete', data: { confirm: 'Are you sure?' }%></p>
<p><%= link_to 'Go back to all days', days_path %></p>

app/views/events/_form.html.erb
<link rel ="stylesheet" type= "text/css" href = "css/new_activity.css">
<%= form_for (@event) do |f| %>



<% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class ="select">
    <p>Day: <%= f.select :day_id, Day.all.map { |day| [ day.to_s] } %></p>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
 <link rel ="stylesheet" type= "text/css" href = "css/new_activity.css">
 <%= render 'form' %>
 
 <% link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Of All Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.body %></td>
        <td><%= link_to event.day_id, days_path(@event) %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_event_path %>
<a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/">Homepage</a>

app/views/events/new.html.erb
<h1>New Event</h1>
<%= render 'form' %>

<%= form_for :event, url:events_path do |f| %>

<% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    
  <% end %>
  
  
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @event.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @event.body %>
</p>
<%= link_to 'Event List', events_path %>


<p><%= link_to 'Delete', @event, method: 'delete', data: { confirm: 'Are you sure?' }%></p>
<p><%= link_to 'Go back to all events', events_path %></p>

app/views/homepage/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title> MENU </title>
        <link rel ="stylesheet" type= "text/css" href = "css/homepage.css">
    </head>
    <body>
        <nav class ="nav">
            <ul class = "menu">
                <li class ="menu_item"><a href= "#">Days</a>
                    <ul class ="submenu">
                        <li class="submenu_item"><%= link_to 'Create Day', new_day_path %></li>
                        <li class="submenu_item"><%= link_to 'View Days', days_path %></li>
                    </ul>
                </li>
                <li class ="menu_item"><a href= "#">Events</a>
                    <ul class ="submenu">
                        <li class="submenu_item"><%= link_to 'Create Event', new_event_path %></li>
                        <li class="submenu_item"><%= link_to 'View Events', events_path %></li>
                    </ul>
                </li>
            </ul>
         </nav>
    </body>
</html>
     
   
        
   
    <body>
        <br><br><br><br>
        <div class = "container">
            <div class ="month">
                <strong> Welcome to MJBC's App! </strong><br><br>
                <strong> April </strong>
                <br>
                <br>
                <strong> 2019 </strong>
            </div>
            <table>
                <tr>
                    <th> Sun</th>
                    <th> Mon</th>
                    <th> Tue</th>
                    <th> Wed</th>
                    <th> Thu</th>
                    <th> Fri</th>
                    <th> Sat</th>
                </tr>
                <tr>
                    <td></td>
                    <td><a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/days/new">1</a></td>
                    <td><a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/days/new">2</a></td>                    
                    <td><a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/days/new">3</a></td>
                    <td><a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/days/new">4</a></td>
                    <td><a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/days/new">5</a></td>
                    <td><a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/days/new">6</a></td>
                </tr>
                
                  <tr>
                    <td><a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/days/new">7</a></td>
                    <td><a href= "https://8b198c22a6ad40ccab545e0e0d546bde.vfs.cloud9.us-east-2.amazonaws.com/days/new">8</a></td>
                    <td>9</td>
                    <td>10</td>
                    <td>11</td>
                    <td>12</td>
                    <td>13</td>
                </tr>
                
                <tr>
                    <td>14</td>
                    <td>15</td>
                    <td>16</td>
                    <td>17</td>
                    <td>18</td>
                    <td>19</td>
                    <td>20</td>
                </tr>
                
                <tr>
                    <td>21</td>
                    <td>22</td>
                    <td>23</td>
                    <td>24</td>
                    <td>25</td>
                    <td>26</td>
                    <td>27</td>
                </tr>
                
                <tr>
                    <td>28</td>
                    <td>29</td>
                    <td>30</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
            
            </div>
    </body>
</html>